### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [awo-ali/Calculator-Project#1]
# Feedback

Hey Charlie here, feel free to message me on Slack if you want any clarification on the points below. I will give you both positive and constructive feedback on your project.

---

## Lets Build

- A working Calculator - DONE
- Practice using Git and GitHub flow - DONE
- Apply what you are learning?
  - SCSS
  - BEM

## Requirements

- PSEUDOCODE - DONE
- Github Repo:
  - README.md - DONE
  - 15 commits - DONE 20 commits
- Accept a minimum of 2 inputs, perform an operation and return the output.
- DO NOT USE `eval()` - DONE
- Mobile-first - KINDA DONE
  - You have some weirdness I will talk about below
- No copying code / using a tutorial as your own work - DONE

---

### Positive

- The UI looks great, you have added some nice effects to it.
- The colors and the gradient look great.
- The hover is a nice touch to indicate you can interact with them.
- Your BEM is almost there `grid-container__equalsButton` would be `grid-container__equals-button`
- Your readme is great, you have started using markdown.
  - I would still recommend having a look at markdown [markdown in 10 mins](https://towshif.github.io/site/04.Organizing-Reporting/markdown/)
  - It will make your projects stand out.

### Constructive

- You have some weirdness with your media queries, this is because in `_grid-container.scss` you have your code in media queries.

```scss
// _grid-container.scss
@media screen and (min-width: 768px) {
  // YOUR STYLES
}

@media screen and (max-width: 420px) {
  // YOUR STYLES
}
```

- This means your styles are being applied over 768px and under 420. This means values between 420 - 768 are not styled. Media queries are only to update styles when you go over a certain breakpoint/device width.

```scss
// _grid-container.scss

// THE STYLES BELOW WILL ALWAYS BE APPLIED
.grid-container {
  height: 600px;
  width: 300px;
  margin: 60px;
  background-color: lightgray;
  border-radius: 25px;
  box-shadow: 5px 10px 18px #888888;
  border: 2px solid black;
  padding: 20px;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-template-rows: 1.5fr 0.5fr 0.5fr 0.5fr 0.5fr 0.5fr;
  grid-template-areas:
    "display display display display"
    "clear percentage delete divide"
    "number7 number8 number9 multiplication"
    "number4 number5 number6 subtraction"
    "number1 number2 number3 addition"
    "number0 number0 decimal equals";
  grid-gap: 1rem;
  background: linear-gradient(to right, rgb(139, 213, 118), rgb(81, 176, 126));
}
// IF I NEED TO OVERWRITE THE STYLE ABOVE AT DIFFERENT BREAKPOINTS -> MEDIA QUERY
@media screen and (min-width: 768px) {
  // IF THE DEVICE IS BIGGER THEN 768 I WILL OVERWRITE THE BACKGROUND COLOR
  .grid-container {
    background: linear-gradient(to right, rgb(255, 89, 0), rgb(204, 255, 0));
  }
}
```

- You have a lot of repetition with your styles

```scss
// _grid-items.scss

.grid-container__number1 {
  grid-area: number1;
  background-color: $secondary-color;
  border-radius: $border-radius;
}
.grid-container__number2 {
  grid-area: number2;
  background-color: $secondary-color;
  border-radius: $border-radius;
}
// YOU DO ^^ FOR EACH NUMBER

// COULD BE

.grid-container__numbers {
  background-color: $secondary-color;
  border-radius: $border-radius;
}
.grid-container__number1 {
  grid-area: number1;
}
.grid-container__number2 {
  grid-area: number2;
}
```

### Positive

- The majority of your functions are small and do one job this is great! Keep them simple :)
- I feel confident with your understanding of variables, control flow, arrays, and loops. You are clearly using them sensibly in the project.
- I am confident in your understanding of the DOM, you are able to get, interact and set up events on your HTML elements.
- You have managed to some functionality into this project, and I can see you are eager to add more. Keep this up and come back and add to it as you go through the course!

### Constructive

- You cannot divide, this has been missed off.

- You can press multiple . e.g 5.5.5.5.5.
- Could you group your variables together and store them in an object?

  - It might make more sense as they are all related.

- Your `Del()` function should be written in camelCasing. So `del()` or something more descriptive `deleteFromDisplay()`.

- You have some repetition in your `calculate()` function. Let's refactor it.

```js
// javascript.js
const calculate = event => {
  if (operatorValue == "+") {
    firstNumber = display.innerHTML.split("+")[0];
    secondNumber = display.innerHTML.split("+")[1];

    display.innerHTML = parseInt(firstNumber) + parseFloat(secondNumber);
  } else if (operatorValue == "-") {
    firstNumber = display.innerHTML.split("-")[0];
    secondNumber = display.innerHTML.split("-")[1];

    display.innerHTML = parseInt(firstNumber) - parseInt(secondNumber);
  } else if (operatorValue == "x") {
    firstNumber = display.innerHTML.split("x")[0];
    secondNumber = display.innerHTML.split("x")[1];
    display.innerHTML = parseInt(firstNumber) * parseFloat(secondNumber);
  } else if (operatorValue == "%") {
    firstNumber = display.innerHTML.split("%")[0];
    secondNumber = display.innerHTML.split("%")[1];
    display.innerHTML = parseInt(firstNumber) % parseFloat(secondNumber);
  }
};

// COULD BE

const calculate = () => {
  // YOU ARE STORING THE OPERATOR VALUE
  // USE IT TO SPLIT IT FIRST -> RATHER THEN DOING EVERY TIME
  const operators = display.innerHTML.split(operatorValue);
  // IT IS EASIER TO READ IF YOU TURN THEM TO NUMBERS WHEN YOU ASSIGN THEM TO VARIABLES
  firstNumber = parseInt(operators[0]);
  secondNumber = parseInt(operators[1]);
  // HERE YOU DO NEED TO MATCH IT SO YOU CAN PREFORM THE ACTION YOU NEED TO
  if (operatorValue == "+") {
    display.innerHTML = firstNumber + secondNumber;
  } else if (operatorValue == "-") {
    display.innerHTML = firstNumber - secondNumber;
  } else if (operatorValue == "x") {
    display.innerHTML = firstNumber * secondNumber;
  } else if (operatorValue == "%") {
    // HOW WOULD YOU WORK OUT THE PERCENTAGE?
    display.innerHTML = firstNumber % secondNumber;
  } // DIVIDE ??
};
```
